general {
    ignore_empty_input = true
}
background {
    path = ~/.config/hypr/wallpaper/01.jpg
    blur_passes = 3
}
input-field {
    size = 200, 30
    position = 0, -400
    inner_color = rgba(255, 255, 255, 0.3)
    outer_color = rgba(255, 255, 255, 0.3)
    font_family = SauceCodePro Nerd Font
    font_color = rgba(200,200,200,1.0)
    placeholder_text =
    check_color = rgba(255, 255, 255, 0.3)
    fail_color = rgba(255, 255, 255, 0.3)
    rounding = 20
    fade_on_empty = false
}
label {
    text = $USER
    color = rgba(255,255,255,1.0)
    font_family = SauceCodePro Nerd Font
    position = 0, -350
}
